### ISSUE TITLE
Documentation Redux

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/fluid-music#116]
The documentation has gotten stagnant. It's time to bring it back and make it better.

As per conversation with @montoyamoraga

- [x] The hook fdf3fc4
    - Show the most with the least
- [x] Setting the conversation
    - examples: [P5 Community](https://p5js.org/community/), [p5js.org](https://p5js.org/)
- [x] There are several "Layers" of documentation. These can be in the linked from the main README
    - [x] 1. Getting Started
    - [x] 2. Describe the "concepts" like "Technique", "Recipe", "Rhythm String"
    - [x] 3. fluid-music API https://fluid-music.github.io
        - [x] TODO: update readme in the fluid-music directory of this repo (which ends up at fluid-music.githubio)
- [ ] Guides - Get to eventually, but not needed immediately 
    - creating and publishing a package (recipe?) from a collection of audio samples
    - creating and publishing a package (recipe?) with a midi-like chords 
    - Using VSTs
    - Writing a VST adapter
    - Building

**Comment by montoyamoraga** [comment]
also, just have one branch, and have it called main :)

**Comment by CharlesHolbrow** [comment]
The default GitHub branch was renamed to 'main' 

Existing local repos can update their references as follows: 

```
# Switch to the "master" branch:
$ git checkout master

# Rename it to "main":
$ git branch -m master main

# Get the latest commits (and branches!) from the remote:
$ git fetch

# Remove the existing tracking connection with "origin/master":
$ git branch --unset-upstream

# Create a new tracking connection with the new "origin/main" branch:
$ git branch -u origin/main
```

I do need to keep the develop branch because not all pushes will be stable, (I want the main branch to always be stable).

**Comment by CharlesHolbrow** [comment]
Screenshot for README

![Screen Shot 2020-12-16 at 1 02 37 AM](https://user-images.githubusercontent.com/1512520/102311683-4baa3b80-3f3b-11eb-87d1-85f4909afb0a.png)

**Comment by CharlesHolbrow** [comment]
Some more documentation images
<img width="1035" alt="Screen Shot 2021-01-10 at 4 06 54 PM" src="https://user-images.githubusercontent.com/1512520/104135377-fc9acf00-535d-11eb-8125-beb7c1b77cb1.png">

<img width="971" alt="Screen Shot 2021-01-16 at 2 33 14 PM" src="https://user-images.githubusercontent.com/1512520/104821154-f4340f80-5807-11eb-80a3-134b4585ffc2.png">

**Comment by CharlesHolbrow** [comment]
This is in reasonably good shape. Will do the guides eventually
