### ISSUE TITLE
Support Audio File playbackRate values other than 1 and -1

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/fluid-music#119]
The `FluidSession` and `FluidAudioFile` data model support `playbackRate` including negative playback rates for playing audio in reverse. 

However, both the Reaper and the Tracktion exporters only support `playbackRate`s  `1` and `-1`. 

- [x] Cyber Server support for non unity-playback rates
- [x] cybr client support
- [x] Tracktion exporter support
- [x] Reaper exporter support

**Comment by CharlesHolbrow** [comment]
The first step is to add OSC handlers for
- `/clip/set/speed` `clip->setSpeedRatio`
- `/clip/set/stretch-mode/`  `audioClip->setTimeStretchMode(te::TimeStretcher::Mode::soundtouchBetter);` (needs guard to ensure that selected clip is an audio clip)

**Comment by zhiweigan** [comment]
For the reaper export, make sure to unselect PreservePitchWhenChangingPlaybackRate.

**Comment by CharlesHolbrow** [comment]
closed by f9c612d5cc6c9a3edf21c65fb408325b13989eee
