### ISSUE TITLE
typedoc: documentation generation

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/fluid-music#120]
I'm using the typedoc `v0.20.0` beta to generate documentation. The output of `v0.20.0` beta is MUCH better than `v0.19.x`

Unfortunately, there is a bug in the current beta version that causes a crash 

This line is throwing an error for me: https://github.com/TypeStrong/typedoc/blob/library2/src/lib/converter/types.ts#L640 'TypeError: Cannot read property 'every' of undefined'

I can fix the error by changing the line to `if (node.elements && node.elements.every(ts.isNamedTupleMember)) {`

For now, I just manually edited the file in the node_modules folder to circumvent the bug. This is not clean workaround. It will do until v0.20.0 comes out of beta. Fow now, this allows us to proceed with #116

**Comment by CharlesHolbrow** [comment]
From the typedoc gitter:

> **Me:** This line is throwing an error for me: https://github.com/TypeStrong/typedoc/blob/library2/src/lib/converter/types.ts#L640 TypeError: Cannot read property 'every' of undefined
> I can fix the error by changing the line to if (node.elements && node.elements.every(ts.isNamedTupleMember)) {
> But I'm not sure if this is the best approach. Happy to make a PR if so.

> @CharlesHolbrow do you have a test case that causes this? node.elements?.every(ts.isNamedTupleMember) would probably be nicer, a PR would be great

**Comment by Gerrit0** [comment]
Someone else reported this on the TypeDoc GitHub - which eventually let me figure out the issue. This was a problem with TS 3.9 support, there is a fix available in 0.20.7 - https://github.com/TypeStrong/typedoc/issues/1439

**Comment by CharlesHolbrow** [comment]
@Gerrit0 Great news, many thanks for following up!
