### ISSUE TITLE
Crashing on plugin: iZRX8De-hum

### ISSUE THREAD

**Issue by blackwood** [CharlesHolbrow/fluid-music#150]
Hey Charles,

Here's the final line of the console log of the output when `cybr --scan-plugins` fails (via cybr-0.3.1-rc1)

> ``` objc[1635]: Class RhubarbComboBoxAccessibility_UniqRX_HUMREMOVAL_8_1_544 is implemented in both /Library/Audio/Plug-Ins/VST/RX 8 De-hum.vst/Contents/Resources/iZRX8De-hum.bundle/Contents/MacOS/iZRX8De-hum (0x15f60a6c0) and /Library/Audio/Plug-Ins/VST3/RX 8 De-hum.vst3/Contents/Resources/iZRX8De-hum.bundle/Contents/MacOS/iZRX8De-hum (0x20fab66c0). One of the two will be used. Which one is undefined.```

It does seem to stop logging on this plugin each time, though I suppose there's a possibility that asynchronicity is throwing me off the scent—if there's a specific error message I should be looking for, let me know. 

The crash message in the Problem Report for cybr also appears to correspond to the iZotope RX8 De-hum plugin:

```
Thread 0 Crashed:: JUCE Message Thread  Dispatch queue: com.apple.main-thread
0   com.izotope.rx                	0x000000020ec31a66 0x20e56a000 + 7109222
1   com.izotope.rx                	0x000000020ef076a5 0x20e56a000 + 10081957
2   com.izotope.rx                	0x000000020eb1bd9f 0x20e56a000 + 5971359
3   com.izotope.rx                	0x000000020ef30e5b 0x20e56a000 + 10251867
4   com.izotope.VST.RX8DHUM       	0x000000020e4ea109 0x20e4e2000 + 33033
5   com.izotope.VST.RX8DHUM       	0x000000020e50c846 0x20e4e2000 + 174150
6   com.izotope.VST.RX8DHUM       	0x000000020e53317b 0x20e4e2000 + 332155
7   cybr                          	0x000000010d1be9d0 0x10d094000 + 1223120
8   cybr                          	0x000000010d583a9d 0x10d094000 + 5175965
9   cybr                          	0x000000010d1d8b0c 0x10d094000 + 1329932
10  cybr                          	0x000000010d0d64cf 0x10d094000 + 271567
11  cybr                          	0x000000010d0c762a 0x10d094000 + 210474
12  cybr                          	0x000000010d0c0d1a 0x10d094000 + 183578
13  cybr                          	0x000000010d232a05 0x10d094000 + 1698309
14  com.apple.CoreFoundation      	0x00007fff206c3a0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
15  com.apple.CoreFoundation      	0x00007fff206c3974 __CFRunLoopDoSource0 + 180
16  com.apple.CoreFoundation      	0x00007fff206c36ef __CFRunLoopDoSources0 + 248
17  com.apple.CoreFoundation      	0x00007fff206c2121 __CFRunLoopRun + 890
18  com.apple.CoreFoundation      	0x00007fff206c16ce CFRunLoopRunSpecific + 563
19  com.apple.HIToolbox           	0x00007fff28949630 RunCurrentEventLoopInMode + 292
20  com.apple.HIToolbox           	0x00007fff28949282 ReceiveNextEventCommon + 283
21  com.apple.HIToolbox           	0x00007fff2894914f _BlockUntilNextEventMatchingListInModeWithFilter + 64
22  com.apple.AppKit              	0x00007fff22ee19b1 _DPSNextEvent + 883
23  com.apple.AppKit              	0x00007fff22ee0177 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
24  com.apple.AppKit              	0x00007fff22ed268a -[NSApplication run] + 586
25  cybr                          	0x000000010d0da32f 0x10d094000 + 287535
26  libdyld.dylib                 	0x00007fff205e6621 start + 1
```

**Comment by CharlesHolbrow** [comment]
@blackwood a big thank you for reporting this bug. VST scanning needs a little work, but because it can be hard to reproduce, reporting the issues is super helpful. Also, note that there is a [v0.3.1](https://github.com/fluid-music/cybr/releases/tag/v0.3.1) (non-release candidate) available, and from here out all releases will be available on github. 

I'm going to move this issue to [cybr](https://github.com/fluid-music/cybr/issues/4), because strictly speaking this is a cybr bug, not a fluid-music bug.
