### ISSUE TITLE
Server: rendering an edit without playing it first creates an empty wave file?

### ISSUE THREAD

**Issue by CharlesHolbrow** [CharlesHolbrow/fluid-music#36]
It seems like trying to render an edit from the server creates an empty wav file if that edit was never played. I observed this behavior once. Double check it.

**Comment by CharlesHolbrow** [comment]
Verified that this is still a bug.

**Comment by zhiweigan** [comment]
Working as of Feb 16 2021. Closed until bug resurfaces.
